version: "1.0"
tables:
  respectccep:
    file_path: "respect_ccep_metadata-pyhealth.csv"
    patient_id: "participant_id"
    timestamp: null
    attributes:
      - "session_id"
      - "run_id"
      - "age"
      - "sex"
      - "participant_session"
      - "events_file_path"
      - "channels_file_path"
      - "electrodes_file_path"
      - "coordsystem_file_path"
      - "vhdr_file_path"
      - "vmrk_file_path"
      - "eeg_file_path"
      - "ieeg_json_file_path"
